name: Run tests

on:
    push:
        branches: ['v0.0.0-alpha']
    pull_request:
        branches: ['v0.0.0-alpha']

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['22.x']

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Required for coverage comment updates in README
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm ci
            - name: Run Tests and Generate Coverage
              run: |
                  npm install -D jest-junit
                  npm test -- --coverage --coverageReporters json-summary --reporters=default --reporters=jest-junit

            - name: Tailscale
              if: failure()
              uses: tailscale/github-action@v2
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:ci

            - name: Jest Coverage Comment
              id: coverageComment
              uses: MishaKav/jest-coverage-comment@main
              with:
                  title: 'Test Coverage Report'
                  coverage-summary-path: ./coverage/coverage-summary.json
                  junitxml-path: ./junit.xml
                  junitxml-title: 'Test Summary'
                  badge-title: 'Coverage'
                  hide-comment: false
                  create-new-comment: false

            - name: Check the output coverage
              run: |
                  echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
                  echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
                  echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

            - name: Create the badge
              if: github.ref_name == 'v0.0.0-alpha'
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
                  gistID: 66dfa344179fb9863c863cb55e5ffc5b
                  filename: jest-coverage-comment__main.json
                  label: Coverage
                  message: ${{ steps.coverageComment.outputs.coverage }}%
                  color: ${{ steps.coverageComment.outputs.color }}
                  namedLogo: javascript

            - name: Send failure email alert
              if: failure()
              uses: dawidd6/action-send-mail@v3
              with:
                  server_address: '100.115.61.18'
                  server_port: '2526'
                  username: 'github-actions@unstaticlabs.com'
                  password: 'not_required'
                  subject: 'Smash-Node-Lib Tests Failed'
                  body: ${{ steps.coverageComment.outputs.summaryHtml }}
                  convert_markdown: true
                  to: 'ci@unstaticlabs.com'
                  from: 'Github Actions'
