# source: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

name: Run tests

on:
  push:
    branches: ["v0.0.0-alpha"]
  pull_request:
    branches: ["v0.0.0-alpha"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
